FROM vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:latest
WORKDIR /workspace

RUN git clone -b v0.6.4-hook-patch https://github.com/PeterYang12/vllm.git

WORKDIR /workspace/vllm

RUN pip install -v -r requirements-hpu.txt

ENV no_proxy=localhost,127.0.0.1
ENV PT_HPU_ENABLE_LAZY_COLLECTIVES=true

RUN VLLM_TARGET_DEVICE=hpu python3 setup.py install

WORKDIR /workspace/

RUN ln -s /workspace/vllm/tests && ln -s /workspace/vllm/examples && ln -s /workspace/vllm/benchmarks

RUN git clone https://github.com/PeterYang12/vllm_Intel_extension.git

COPY entrypoints/start.sh /workspace/
ENTRYPOINT ["bash", "start.sh"]